### ISSUE TITLE
Prototype Scenery support

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#101]
Another meme one. kek

Format of the 1st item is the same as the final version (though I think there's only format A texture info structures).

Format of the 2nd and 3rd items are different: 2nd item is made up by a list of 12-byte structures, while the 3rd item is made up by a list of 4-byte structures. Color shading for vertices wasn't implemented at the time.

**Comment by ghost** [comment]
please add texture support for prototype level2 and levelg...

**Comment by ManDude** [comment]
what
