### ISSUE TITLE
Normal rendering

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#109]
Option to toggle rendering normals in the Crash 1 animation entry viewer.

Why do these even exist!?

**Comment by NetyashaRoozi** [comment]
What? Normal maps? I don't think crash bandicoot 1 has normal mapping

**Comment by ManDude** [comment]
Yes it does. It just doesn't do anything in-game (not that I know at least).

**Comment by NetyashaRoozi** [comment]
Huh, weird

**Comment by warenhuis** [comment]
The normals are for shadowing. It is used to determine how much darkened the vertex colors must be, depending on where the 'lighting' comes from. Look at Crash in CB1 if you turn him around. The shadow stays on the left side (or the right side depending on the level).

**Comment by ManDude** [comment]
Alright.
