### ISSUE TITLE
When Building Source Code I get "The referenced component 'OpenTK' could not be found"

### ISSUE THREAD

**Issue by NetyashaRoozi** [cbhacks/CrashEdit#111]
Warning 1   The referenced component 'OpenTK' could not be found.  
Warning 2   The referenced component 'OpenTK.GLControl' could not be found.  
Error   3   The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\OldSceneryEntryViewer.cs    7   7   CrashEdit
Error   4   The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\OldSceneryEntryViewer.cs    8   7   CrashEdit
Error   5   The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\OldSceneryEntryViewer.cs    9   7   CrashEdit
Error   6   The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\ThreeDimensionalViewer.cs   7   7   CrashEdit
Error   7   The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\ThreeDimensionalViewer.cs   8   7   CrashEdit
Error   8   The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\ThreeDimensionalViewer.cs   9   7   CrashEdit
Error   9   The type or namespace name 'GLControl' could not be found (are you missing a using directive or an assembly reference?) C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\ThreeDimensionalViewer.cs   13  52  CrashEdit
Error   10  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\OldAnimationEntryViewer.cs  7   7   CrashEdit
Error   11  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\OldAnimationEntryViewer.cs  8   7   CrashEdit
Error   12  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\OldAnimationEntryViewer.cs  9   7   CrashEdit
Error   13  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\EntityEntryViewer.cs    7   7   CrashEdit
Error   14  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\EntityEntryViewer.cs    8   7   CrashEdit
Error   15  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\EntityEntryViewer.cs    9   7   CrashEdit
Error   16  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\SceneryEntryViewer.cs   7   7   CrashEdit
Error   17  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\SceneryEntryViewer.cs   8   7   CrashEdit
Error   18  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\Harley\Desktop\Desktop Items aka Junk\Game Ripping\CrashEdit-master\CrashEdit\Controls\SceneryEntryViewer.cs   9   7   CrashEdit
Warning 19  Could not resolve this reference. Could not locate the assembly "OpenTK.GLControl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  CrashEdit
Warning 20  Could not resolve this reference. Could not locate the assembly "OpenTK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    CrashEdit

I get this when trying to build the source, I was trying to build it with the Crash-Bandicoot-2-Modelexport "Addon", Yes I did follow instructions

**Comment by ManDude** [comment]
You're missing OpenTK.

You can either download OpenTK or tell Visual Studio (or whatever you use) to use the OpenTK DLL's included in CrashEdit.zip.

**Comment by ughman** [comment]
What he said.

http://www.opentk.com/

**Comment by ughman** [comment]
There's actually a chance it might not be able to find OpenTK, in which case you can delete it from the project references and readd it.
