### ISSUE TITLE
Animation offset support

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#113]
Some animations look misplaced and weird if offsets aren't taken into account (plus it's technically part of the animation itself). If you add support for them (which I did, locally) the editor actually centers the view properly.

**Comment by NetyashaRoozi** [comment]
I can't even view anything in the new (New Gui) version and this GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit); showed this Attempted to read or write protected memory. This is often an indication that other memory is corrupt. after running it in visual studio

**Comment by ManDude** [comment]
<s>Delete that line of code and</s> use OldMainForm, the new one is incomplete.

**Comment by NetyashaRoozi** [comment]
it wont let me, says I cant edit 64 bit programs

**Comment by ManDude** [comment]
wot

**Comment by ughman** [comment]
It's telling you that you can't modify the program's source code while it's running. It's a limitation of the x86-64 target in visual studio for some reason, not really sure why

**Comment by NetyashaRoozi** [comment]
Huh strange, It wasnt running at the time, I guess a process of it was running in the background

**Comment by NetyashaRoozi** [comment]
Huh strange, It wasnt running at the time, I guess a process of it was running in the background

**Comment by NetyashaRoozi** [comment]
Huh strange, It wasn't running at the time, I guess a process of it was running in the background, also what is the code for the OldMainForm

**Comment by ManDude** [comment]
Replacw "MainForm" in "Program.cs" to "OldMainForm".
