### ISSUE TITLE
3D Model view?

### ISSUE THREAD

**Issue by AraHaan** [cbhacks/CrashEdit#115]
I was wondering if it is possible for 1 day have the models be 3D view also I think the Senceries in Crash 3 would look best if the Editor had a 3D view option to fiew the whole map at 1 time. And hopefully with 3d Model support actually loading the models up in the zone views instead of the images currently used but then again the images currently used can be backups in case something actually does indeed go wrong.

**Comment by ManDude** [comment]
This is split into other issues (can't recall their IDs so screw it).

**Comment by ughman** [comment]
Yeah I've been thinking about having this, like some kind of button at the top you hit to switch to a more typical editor mode you'd expect like in lunarmagic or doom builder. Need to get the current editor stuff properly working again first though.

**Comment by AraHaan** [comment]
oh and I was also thinking since I know of a Program that can view 3D models I think viewing the models themselves can be done with help of SlimDX. I happen to use PMDEditor that just so happens to depend on that. You could prob instead use it for Sceneries and zones. Not sure if and how well it would work but it is definately worth a look and test.

**Comment by AraHaan** [comment]
@ManDude, @ughman sorry it been so long but; did you guys figure out the model compressions yet and if so how can one (like me) decompress them on the ones in crash 2 and 3?
