### ISSUE TITLE
Help with Everything

### ISSUE THREAD

**Issue by ghost** [cbhacks/CrashEdit#124]
I have no idea how CrashEdit works, let alone how to start it. (I cannot find the file) is there any tutorial somewhere to help me learn all this?

EDIT: Got it to start, downloaded the wrong version. But I'm still very confused, as I cannot find an nsf file of Crash 2 anywhere, all I find is a .bin file.

**Comment by ughman** [comment]
The BIN file you have is probably a ripped CDROM image. You will need to extract the files from it. The best way may be to mount the image using a virtual CD tool or whatever you have available for your platform. For windows I've used MagicDisc in the past, looks like the site is down right now but it will probably come back at some point.

* http://magiciso.com/tutorials/miso-magicdisc-overview.htm
* http://66.39.114.223/tutorials/miso-magicdisc-overview.htm

To play your mod you will need to build another BIN from your extracted files (keeping the same directory structure as well). This will need to be in MODE2/FORM1 format (usually this is __not__ the default setting) for most PS1 emulators as well as actual PS1 and PS2 hardware (for hardware you will need a softmod or modchip anyway). I don't recommend any particular tool for this, I think most people are using something called UltraISO but I can't remember. Most of these programs have similar names which doesn't help.

You may have some success using this program without any options enabled:

* https://www.wobbyworks.com/CrashHacks.zip -- important: these dlls are incompatible with the ones used in most verisons of CrashEdit so put it in a separate folder

This program will output a correct format BIN but the ECC/EDC data will be incorrect which will throw off some emulators. You may be able to fix that by dropping the erroneous output BIN onto this program:

* http://www.romhacking.net/utilities/1264/

Also, I believe mednafen may also want a license file applied to the image as well. That's another interesting dilemma on windows.

On my linux system I currently use the following method:

Extracting from bin:

1. `bin2iso` by Neill Corlett to convert the BIN to an ISO.
2. 7zip to extract files from the ISO file. (alternatively use losetup and mount)

Creating new bin:

1. CrashHacks linked above to create crippled BIN.
2. `error_recalc` from above to fix ECC/EDC
3. `dd if=usalicense.dat of=my_modded_game.bin conv=notrunc` license file from any unofficial ps1 homebrew sdk such as psxsdk. License file varies by game region (US/EU/JP).

**Comment by supermariosunshine2002** [comment]
How do you actually Mod the Game?

**Comment by ughman** [comment]
1. Extract the game files from the game disc (NSF, NSD, CNF, and the exe with name such as SCUS_123.45).
2. Edit game files (NSF primarily) using CrashEdit or other applicable tools.
3. Build a new disc in MODE2/FORM1 format containing a standard ISO9660 filesystem (no extensions needed such as joliet, rock ridge, level 2, etc). Most programs provide this new disc image as a pair of BIN and CUE files.
4. (maybe optional) Apply the necessary license file to the beginning of the BIN image. License files can be found here https://github.com/simias/psxsdk/tree/master/licenses . Many emulators do not require it (ePSXe, XEBRA, swap trick on a real PS2), some do (mednafen?).
