### ISSUE TITLE
A bit new here, just want to look at some of the models and levels, need help opening the app.

### ISSUE THREAD

**Issue by patliatli** [cbhacks/CrashEdit#125]
How do I open the program? Searched everywhere and can't find it.

**Comment by ughman** [comment]
Try this version: https://www.wobbyworks.com/CrashEdit_mdude.zip

You can get the source code here: https://github.com/mandude/CrashEdit/

**Comment by patliatli** [comment]
The models still just show up as HEX code. Am I doing something wrong?

**Comment by ManDude** [comment]
I might've not pushed some changes I've made related to models. Check again now.

**Comment by patliatli** [comment]
I noticed that Crash Edit has an option for the 1995 prototype. Where can i get the files for the prototype that work with crash edit?

**Comment by ManDude** [comment]
they're level2 and levelg in the crash 1 prototype (although even those 2 have different formats... oh well). I don't remember the ID for the 3rd level.
