### ISSUE TITLE
Chunk size Counter

### ISSUE THREAD

**Issue by ghost** [cbhacks/CrashEdit#129]
Will it be possible to add a Chunk size counter in the '' Crash Editor ''? This will be very useful.

**Comment by warenhuis** [comment]
In ManDude's fork of CrashEdit (with a lot of added functionality) you can view how many bytes are used for data/empty in a chunk as well as the size of the individual entries if you click on the chunk's name.
https://github.com/ManDude/CrashEdit

**Comment by ManDude** [comment]
Yeah it's a really hacky implementation, and I don't think it updates live either (and there's some other weird minor issues) but it does its job.

**Comment by ughman** [comment]
Solved in #139
