### ISSUE TITLE
I'm a beginner, help me

### ISSUE THREAD

**Issue by ghost** [cbhacks/CrashEdit#130]
It is possible to transport the areas of Crash Bandicoot 2 to Crash Bandicoot 3?
How do I change the texture of the entrance portals of Crash Bandicoot 3 Warped?

**Comment by ughman** [comment]
Transporting areas between different games is very experimental, we're just now starting to mess around with this idea. The scenery model and zones are very close in compatibility but there are some important differences which haven't been properly worked out yet.

Changing the texture for an entrance portal in Crash 3 may require editing the VIDO entries (T21), which there is currently no editor for.
