### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by TheRealCreatorC** [cbhacks/CrashEdit#131]
I have two questions, and i will hope that someone will answer them.

1. When i sometimes duplicate entities, and try to save, it will sometimes say:
A packing error occured. One of the entry-containing chunks contains over 64 KB of data.

2. How can you change the box count (for the box counter at the end of the level), like from 62 boxes to 63 or 23 or basically anything?
If someone could answer these i would be really happy.

**Comment by TheRealCreatorC** [comment]
EDIT: Found out that the chunks can only contain 64 KB of data, but then, how can some people create levels with like over 500 boxes?

**Comment by awe777** [comment]
1. Yes, 1 chunk only can have 64 kB of data. Doesn't mean that we can't add more chunks onto the level (and that's exactly what they did)

2. Look up Crash's spawn point (obj_willie); that object holds the box count number. Yes, you can turn that box count to negative.

**Comment by TheRealCreatorC** [comment]
Ok, i'll try that later.

**Comment by TheRealCreatorC** [comment]
Wait, how do you add Normal Chunks and then add Entity Entries and then add like nitro crates to them?

**Comment by ManDude** [comment]
you can only add chunks

**Comment by TheRealCreatorC** [comment]
How do i add chunks then?
And how do some people have like a million nitro crates but i can have like 4?

**Comment by ughman** [comment]
You can right-click the NSF in the tree on the left and add a chunk that way. Then, you can drag and drop entries to move them into your new chunk. When you do this you must also click "Patch NSD" in the toolbar at the top of the window to account for the new chunk and the relocated entry.

The game engine has a limit on the number of chunks which can be loaded in ram at any one point, so you cannot simply drop every entry into a separate chunk. Some levels or areas are very close to this limit already while others have more room available.

**Comment by TheRealCreatorC** [comment]
Thanks alot for the help ughman!

**Comment by TheRealCreatorC** [comment]
Hold on; got a new problem: When i add chunks, they'll go so down that i can't drag and drop entities from a chunk to another chunk. Help?

**Comment by ManDude** [comment]
Drag them to a chunk you can see and scroll down until you get it where you want.

**Comment by TheRealCreatorC** [comment]
Thanks! Now i'm ready to make some better mods...

**Comment by TheRealCreatorC** [comment]
And now, i still have one more problem:
I can't drag and drop entities from a entity entry to my new chunk. This might be the last problem.

**Comment by ManDude** [comment]
You cannot do that, no.

**Comment by TheRealCreatorC** [comment]
Okay... but wait, if i have a chunk (like some random chunk from snow go) and i have the created chunk, how i can get entities to it if i can't drag and drop entities from a entity entry to the new chunk?

**Comment by ughman** [comment]
You have to move the entire entry.

**Comment by TheRealCreatorC** [comment]
Okay, thats kinda weird, but anyways, thanks for the help!
