### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by spacedude359** [cbhacks/CrashEdit#132]
What that means "A packing error occurred. One of the entry-containing chunks contains over 64 KB of data."

How to fix.

**Comment by ManDude** [comment]
It means one of the chunks is overflowing with data. Read the readme.md

**Comment by ughman** [comment]
Each chunk is 64KB in size. If the total size of your entries exceeds this amount, the chunk cannot be saved into an NSF file. You can try to reduce the size of the chunk by cutting back on the amount of stuff in the various entries, or you can move some entries into another chunk (possibly a new one you create). In that case you will also need to use the Patch NSD button.

**Comment by TheRealCreatorC** [comment]
You can only have 64 KB of data in each chunk, and if one of the chunks contains over 64 KB of data, that message will pop up.

**Comment by spacedude359** [comment]
Ok, Thanks.
