### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by agsdoom** [cbhacks/CrashEdit#133]
Im using cras edit 1/2/3 windows version but how do i add those updats  i extract some models from vrash bandicoot 3  but some models  are broken and idk-.:I  
![image](https://user-images.githubusercontent.com/43580521/46025482-b28c7180-c0f1-11e8-9aa0-35e64b027fef.png)
this item file name is item
From s1 05 folder -   Ne15G there is NE15G and Ne15V and NE15V  i tryed both diffrent ways  ressult is one Ne15G dsnt work with NE15V it works Ne15V  and i get this broken box happened many models like this idk what is the problem can u help me at discord or somthng ? :I or explain to me i have extracted so many models allrdy but sometimes i get those broken idk :I and some models dont have V  just have model  G and cant find V to extract that model :I just add me discord agsdoom#5879

**Comment by ManDude** [comment]
not really sure what the problem is here, what are you using to extract the models anyway? Anyway, the model-animation links are stored in the code entries (T11), check their items and press Z to toggle EID view mode and see if you can find model-animation links from there.

**Comment by agsdoom** [comment]
using > CrashEdit-v0.10.zip   >   https://www.dropbox.com/sh/yv93g4wsdde32s3/AADko-TdXnhWdDHSsXd6maEoa  

and model extractor    https://github.com/warenhuis/Crash-Bandicoot-2-Modelexport

im using win 10 

do u mean T1 enitrt (ME17V)
                                 (ME17G)

  ? ive ripped 1,2gb models allrdy :I but some models are broken 1 2 some times just s1 s2 s3 folders to go  hehe :D

**Comment by ManDude** [comment]
First off, you should get the build that's actually hosted here: https://builds.crashedit.cbhacks.com/appveyor/build-10002/CrashEdit-10002-819a3f4e96dfcba9339676b8762759548397e74f.7z

Second, I do mean Z and I do mean T11 entries. For Crash 3, those contain the links between models and animations.

**Comment by agsdoom** [comment]
oh oky

**Comment by agsdoom** [comment]
hmm i dont kinda understand :I

**Comment by agsdoom** [comment]
i can find only BLi2G and V cant find T11  z ? :I

**Comment by AraHaan** [comment]
Also you might want to know that the models in Crash 2 and 3 are compressed. Well some of them are. I wish I knew how they are compressed exactly though.

**Comment by agsdoom** [comment]
oh thts why i get those wierd broken boxs :D

**Comment by agsdoom** [comment]
but i dont need animations i just take frame and model i do my self animations riged meh :D

**Comment by ManDude** [comment]
Animations are made of frames.

**Comment by agsdoom** [comment]
i know but i make m own animations i rig model and then make animation and i cant extract 10 diffrent frames at same time can only put one frame and models

**Comment by agsdoom** [comment]
and V still dosent work
