### ISSUE TITLE
hello need help with  No frame in model

### ISSUE THREAD

**Issue by agsdoom** [cbhacks/CrashEdit#134]
hey i need help some models have no frame like BS20G  i cant find BS20V 
no frame
item0 
item1
item2
item3
item4
how to i extract t without frame ?

**Comment by ughman** [comment]
For crash 2, you should be able to find it without issue. For crash 3, BS20G is used with BS10V instead.

**Comment by agsdoom** [comment]
oh oky thnk you i try it and let u know ! :)

**Comment by agsdoom** [comment]
it seems like working but model does not load texture! :O
