### ISSUE TITLE
Can't see scenery, only fruits, boxes and other things

### ISSUE THREAD

**Issue by TheRealCreatorC** [cbhacks/CrashEdit#138]
How can i see scenery?

**Comment by ughman** [comment]
Try this version https://builds.crashedit.cbhacks.com/appveyor/build-10009/CrashEdit-10009-907799b834e3c0c394ee9dfe633b0ec7e900d1e0.7z

**Comment by TheRealCreatorC** [comment]
Thanks! Now i can see the scenery!
