### ISSUE TITLE
Add ability to replace items with exported items.

### ISSUE THREAD

**Issue by AraHaan** [cbhacks/CrashEdit#144]
I think anotherthing I would like to Add (I can add it to a fork and pull request it if needed) On items exported by unpressessing or from the MysteryBox I think should be able to be imported to replace the selected entry. Ofc the exporter would need to be smart enough to only export / import the actual data and not the entry name / info itself that makes the node to avoid issues on the game itself. (Where cases where you want to export an scenery from Crash 3 Alpha warproom to replace the Crash 3 Final warp room scenery wise).

Same thing can be said for the texture chunks.

**Comment by ManDude** [comment]
?
![image](https://user-images.githubusercontent.com/7569514/71528052-e5fe1300-28d5-11ea-897d-f59a31a24a02.png)

**Comment by AraHaan** [comment]
O I did not see that one there. I was thinking more of the lines on the process entries themselves without having to unprocess them so that way it filters out any problems later on the chunk stuff and whatnot that provides the EID, etc.

**Comment by ManDude** [comment]
You can rename an entry by right-clicking it and pressing "Rename Entry"
