### ISSUE TITLE
Bin export problem.

### ISSUE THREAD

**Issue by RobcioRobcio** [cbhacks/CrashEdit#148]
Hello, I've been finishing mod for Crash Bandicoot 2. I exported it to "bin" file which took over 20 minutes to process. After finishing it the file size was 29,4 GB. I tried to launch the game on the ePSXe emulator but nothing happened. Maybe somebody can help me?
![crash](https://user-images.githubusercontent.com/63557429/79752933-5c0b0780-8315-11ea-9b34-c53d0ddb6de1.PNG)

**Comment by ManDude** [comment]
The Make BIN option simply grabs EVERYTHING that's inside the specified folder.

Keep in mind PS1 CD-ROMs cannot contain more than 700MB of data.

**Comment by RobcioRobcio** [comment]
Thanks!
