### ISSUE TITLE
Is it possible now to rip textures and export animations of Crash 1?

### ISSUE THREAD

**Issue by Othman1992** [cbhacks/CrashEdit#151]
If not, will it ever be? I mean how is it looking so far in regards to Crash 1 in general?
Is there a way to export these vertex frame animations and bind them to an OBJ file to work on Maya or Blender?
Thanks!

**Comment by ManDude** [comment]
There is a texture viewer in the program that includes ripping functionality. Just double-click on the visual for the texture chunk.

**Comment by Othman1992** [comment]
If you're referring to these scattered Texture Chunks, I can't export them correctly. And they all seem to appear glitched in the viewer.
As for the 3D object itself I can't export the textures, it says "Texture and color information will not be exported".

**Comment by ManDude** [comment]
you didn't even double-click them

**Comment by Othman1992** [comment]
I did double-click them. It's exactly as I told you: distorted/glitched textures appear on the "Texture Viewer" window! They extract PNGs of about 4 by 4 random pixels. That's why I said I can't export them correctly!

![WillT_0_1](https://user-images.githubusercontent.com/52607540/86493694-1e961200-bd7b-11ea-81d2-dc8cbd2d42ee.png)

**Comment by ManDude** [comment]
You obviously need to tune the various settings there.

**Comment by Othman1992** [comment]
Thanks I guess?... I'll keep this issue open so that other collaborators might help.
