### ISSUE TITLE
Please, help me! (Sorry for bad English, by the way im trying to find the ''beginning zone'')

### ISSUE THREAD

**Issue by Slayerbits** [cbhacks/CrashEdit#153]
Okay, so I'm new in CrashEdit and I'm trying to find the ''Zone'' but I cant find it, I thought it was a problem from the game but it wasn't, please help me.

**Comment by ManDude** [comment]
CrashTest?

**Comment by Slayerbits** [comment]
I mean CrashEdit

**Comment by Slayerbits** [comment]
The problem is that i cant find the beginning zone

**Comment by Slayerbits** [comment]
> CrashTest?

CrashEdit*

**Comment by ManDude** [comment]
Why do you need to find the beginning zone?

**Comment by Slayerbits** [comment]
Because I'm new at CrashEdit, so it would help me.

**Comment by Slayerbits** [comment]
I don't know what i did wrong

**Comment by ManDude** [comment]
Sorry, I do not understand what you're trying to do.

**Comment by Slayerbits** [comment]
Okay, so the problem is that i cant find the ''Zone'' it's the beginning Zone, i just found chunks and all that stuff.

**Comment by Slayerbits** [comment]
![image](https://user-images.githubusercontent.com/70988268/92860598-d1639b80-f3ce-11ea-83d6-cd8306bbf9d4.png)

**Comment by Slayerbits** [comment]
![image](https://user-images.githubusercontent.com/70988268/92860691-ec361000-f3ce-11ea-9980-945092e10598.png)

**Comment by ManDude** [comment]
You're using an old version of the program. The readme says you can find the builds at http://www.cbhacks.com/crashedit.html
