### ISSUE TITLE
A lot of errors when opening NSF on Crash 1

### ISSUE THREAD

**Issue by koopthekoopa** [cbhacks/CrashEdit#155]
Hi, I was planning to do a crash bandicoot 1 mod but when i open a
NSF file it pops up alot of errors.

These are a few of the errors:
![image](https://user-images.githubusercontent.com/61279093/103477164-d0a6a900-4db3-11eb-9c7c-cc98fb0fe26b.png)
![image](https://user-images.githubusercontent.com/61279093/103477166-d7cdb700-4db3-11eb-8c7f-b6f12d7b1bd8.png)
![image](https://user-images.githubusercontent.com/61279093/103477168-dbf9d480-4db3-11eb-8be8-2219358be1d7.png)
![image](https://user-images.githubusercontent.com/61279093/103477171-e025f200-4db3-11eb-8bd2-2ad63f45f087.png)

Am I doing it wrong, is the rom invalid or is it a bug?

**Comment by ughman** [comment]
From this I would guess you've selected the wrong game version in the game version selection window. Which file have you attempted to open?

**Comment by ManDude** [comment]
It looks like you're using a very old version of the program, and also did not select the correct game when opening the NSF. Try downloading the latest build at http://www.cbhacks.com/crashedit.html

**Comment by koopthekoopa** [comment]
> From this I would guess you've selected the wrong game version in the game version selection window. Which file have you attempted to open?

The NSF file.



> It looks like you're using a very old version of the program, and also did not select the correct game when opening the NSF. Try downloading the latest build at http://www.cbhacks.com/crashedit.html

Ah ok.
