### ISSUE TITLE
help with level names

### ISSUE THREAD

**Issue by matheusandradecrashb** [cbhacks/CrashEdit#157]
How do i change the level names in CB3? I saw a mod that changed it, and i'm so sorry if it's not by CrashEdit to do it.

**Comment by ManDude** [comment]
You need to edit text entries in the GOOL files. This isn't really related to CrashEdit since you need to edit them externally (you can however export the entries or items, edit them, then import them back).

**Comment by matheusandradecrashb** [comment]
and are these specific gool files in the warp room .nsf or in each level one?
