### ISSUE TITLE
Crash 1 object support

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#31]
Objects in Crash 1 (all versions) are significantly less complicated and are also way smaller. They have some sort of Int16 that pretty much says how they will show up (after 4 empty bytes with unknown purpose), then ID, then something that says that it's an object and not anything else, then 3 special settings (all of what I listed is in Int16, not sure if they're signed or not), then a byte for type followed by a subtype, then positions: Int16 for X, Y and then Z, followed by more positions if they exist. Note: there must be an extra empty (unsigned?) Int16 if an object has more than 1 position (so you'll have 2 empty Int16 instead of only 1). The editing box fro this should be pretty simple to code, but I don't know where the draw lists (or load lists for that matter, if they exist) are, so I guess there's not much that can be done.

Edit: Ninja'd by #30 I think.

**Comment by ughman** [comment]
Heh, yeah. I'll refer to your notes though.
