### ISSUE TITLE
"Rename Entry" option

### ISSUE THREAD

**Issue by ughman** [cbhacks/CrashEdit#37]
Pretty simple. The real question is, should it also be able to go around and update all of the references to itself to use the new name? Potentially a search-and-replace EID's menu option could be added for that.

**Comment by ManDude** [comment]
Or after renaming the entry it checks every entry (that actually uses it, who knows maybe an animation or camera reference this entry but is not interpreted as such in the game) with the old name and replaces it with the new name.
