### ISSUE TITLE
Password-protect NSF files

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#52]
Creates a "fake" entry type that the game doesn't use, that contains an encoded password (encoding can be similar to the EID encoding). When an NSF file with this is tried to be opened with CrashEdit, it will ask for the (decoded) password. This is just basic protection so that most people don't mod your mods to give false information and stuff.

**Comment by ughman** [comment]
I don't think I can support this feature, it's basically DRM. You're better off doing something like applying a simple XOR encryption to the entry headers and then modifying the game EXE to decrypt them when the chunks get loaded.
