### ISSUE TITLE
CUE/BIN and ISO generator

### ISSUE THREAD

**Issue by ughman** [cbhacks/CrashEdit#59]
There should be an option for creating a playstation console- and emulator-compatible disc image from a directory. I think creating these images is one of the biggest barriers of entry to editing levels, so if CrashEdit was able to do it on its own, that would be a big help.

DiscUtils is apparently garbage, so I'll likely need to write my own code for creating the ISO 9660 filesystem.

**Comment by ManDude** [comment]
What about CCD/IMG/SUB?

**Comment by ughman** [comment]
I can do that if it turns out to be beneficial.

I'm not sure how the NTSC-J versions store their hidden videos, but if it's as a separate CD track then I probably won't support it at first.

**Comment by ManDude** [comment]
Aren't they in IKI format or something? Inside the BANJ_M folder (for Crash 3 at least).
