### ISSUE TITLE
Fix z-fighting

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#63]
Why does it even happen?

**Comment by ManDude** [comment]
Increasing the variables for left, right, bottom, top and zNear (by 10x or 100x) at line 253 in ThreeDimensionalViewer.cs fixes this.

**Comment by Almamu** [comment]
This should be fixed with that pull request. Hope ughman sees this and merges it

**Comment by ManDude** [comment]
I feel like 0.1 is too much. I use 0.01 and it works fine.

**Comment by Almamu** [comment]
Yeah 0.01 should be enough but for some reason I still had some zfighting issues at 0.01 when looking at models so 0.1 looks like did It for good.

**Comment by ManDude** [comment]
Fixed in #159

Turns out we were originally using a 16bit depth buffer instead of 24bit.
