### ISSUE TITLE
Cannot open Crash Bandicoot 2

### ISSUE THREAD

**Issue by francot514** [cbhacks/CrashEdit#68]
Hey, i cannot open crash bandicoot 2 files, i got "reference to object"

**Comment by ManDude** [comment]
Elaborate please?

**Comment by francot514** [comment]
What you mean elaborate??, just have this bug, and cannot edit my crash bandicoot 2 files, when trying to open it from the program, this is complete error message;
 "object reference not set to an instance of an object" at  Crash.EntityBasicPropertyLoader`1.Load(Byte elementsize, Int16 unknown, Byte[] data)

**Comment by ManDude** [comment]
What are you doing exactly?

**Comment by francot514** [comment]
Just extracted game files, open the nsf file with program and select Crash bandicoot 2 choice, after got the error...

**Comment by ughman** [comment]
What level file specifically, and which version of the game (NTSC-U/C, PAL, NTSC-J)? I haven't had this specific issue before, and previously ran tests on all game files to ensure they would open and save.

Also, which version are you using?

**Comment by francot514** [comment]
Any level file, and ntsc-u/c version of the game..

**Comment by ManDude** [comment]
Have you checked permissions?

**Comment by francot514** [comment]
Yes, i have, im using CrashEdit v.10, is latest one?

**Comment by ManDude** [comment]
No, there is a slightly more updated version out there: http://cheek.us.to/CrashEdit.zip

**Comment by francot514** [comment]
Ok good this version worked, now where should i look for some editing guide...
