### ISSUE TITLE
Fix NSD patching

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#69]
It doesn't quite work if you add or remove entries. Also does not update entry count.

**Comment by francot514** [comment]
Is the same issue  as cloning entries?? i got error when doing it...

**Comment by ManDude** [comment]
You can't clone entries, and no this does not give an error message or anything. It's a bug.

**Comment by francot514** [comment]
Sorry, i got confused with entries and entities...

**Comment by NetyashaRoozi** [comment]
For me it gives me a thing saying (Cant be more then 64 kb) is that the same for you?

**Comment by ManDude** [comment]
That's not a bug.
