### ISSUE TITLE
Sounds are ether low pitch or high pitch

### ISSUE THREAD

**Issue by NetyashaRoozi** [cbhacks/CrashEdit#75]
Yeah its a minor problem and I know almost all the games have different values but maybe a bit more customization (A box so you can input a value with a default value)

**Comment by ManDude** [comment]
Sort of adressed in issue #60.

You can always add more buttons yourself (most Crash 2 sounds are between 9000-10000Hz, Aku Aku get sound is in 14kHz or around that).
