### ISSUE TITLE
Fix Crash.UI.csproj

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#81]
It's broken (around line 86 I think) and therefore can't be converted and trying to open newgui is impossible. This is the error I get after conversion:
<code>Crash.UI\Crash.UI.csproj: Error on line 3317816. Expected 'ENCODING' but found 'utf-8'.</code>
Not really useful.

**Comment by ManDude** [comment]
Commenting out the missing files from the project file fixed this.

**Comment by ughman** [comment]
Yeah this was some garbage that slipped through in a partial commit. I've had it fixed locally for a while. I'll close this once I push it.

**Comment by ughman** [comment]
Fixed in a1c13568418f551f26b0b0c21179cef87a168649
