### ISSUE TITLE
Ripped Textures and sprites are all glitchy

### ISSUE THREAD

**Issue by NetyashaRoozi** [cbhacks/CrashEdit#94]
In crash 1-3 all the textures are really glitchy especially the colored option, its just .... corrupted

**Comment by ManDude** [comment]
No it's not, it's how they're loaded in-game. CrashEdit displays them as 16-bit images, and texture chunks can contain 4-bit and 8-bit textures too. In Crash 2's title screen and Pinstripe, you can see some 16-bit textures.

**Comment by ughman** [comment]
It's not meant for that. The colored option is to display the image as 16-bit "direct" images. Most of the textures in crash are 8-bit (or 4-bit?) "indexed" images so that view won't work.
