### ISSUE TITLE
Basic unit testing (load+save NSF's, compare checksum)

### ISSUE THREAD

**Issue by ughman** [cbhacks/CrashEdit#97]
I previously had an external project named CrashTest which would load and save every NSF file and then compare them to make sure I hadn't broken anything. I'll be reimplementing this, maybe using something like NUnit.

**Comment by AraHaan** [comment]
Also keep in mind that the USA version does not have to have the checksum recalculated as it is not used. As far as I am aware.

**Comment by ManDude** [comment]
Yes we know, it's PAL-only.
